using System.Collections.Generic;
namespace CloudHop
{
    // Required keys and argument counts. Visible copy is owned by UITexts.xlsx.
    public static class UITextSchema
    {
        public static readonly IReadOnlyDictionary<string, int> Arguments = new Dictionary<string, int>
        {
            { "common.start", 0 },
            { "common.back", 0 },
            { "common.settings", 0 },
            { "common.home", 0 },
            { "common.retry", 0 },
            { "common.next", 0 },
            { "common.next_stage", 0 },
            { "common.rankings", 0 },
            { "lobby.title", 0 },
            { "lobby.practice", 0 },
            { "lobby.ranking", 0 },
            { "character.title", 0 },
            { "character.select", 0 },
            { "character.selected", 0 },
            { "stage.title", 0 },
            { "stage.name.0", 0 },
            { "stage.name.1", 0 },
            { "stage.name.2", 0 },
            { "stage.level.0", 0 },
            { "stage.level.1", 0 },
            { "stage.level.2", 0 },
            { "hud.jump", 0 },
            { "pause.title", 0 },
            { "pause.resume", 0 },
            { "settings.volume", 0 },
            { "settings.muted", 0 },
            { "settings.sound_on", 0 },
            { "result.clear", 0 },
            { "result.over", 0 },
            { "result.all_clear", 0 },
            { "result.new_run", 0 },
            { "result.outside_top", 0 },
            { "result.retry_hint", 0 },
            { "name.title", 0 },
            { "name.subtitle", 0 },
            { "name.error", 0 },
            { "name.rules", 0 },
            { "hud.practice", 0 },
            { "ranking.title", 0 },
            { "ranking.rank", 0 },
            { "ranking.nickname", 0 },
            { "ranking.time", 0 },
            { "ranking.note", 0 },
            { "ranking.empty_name", 0 },
            { "ranking.empty_time", 0 },
            { "character.name.0", 0 },
            { "character.name.1", 0 },
            { "character.name.2", 0 },
            { "hud.score", 1 },
            { "hud.best", 1 },
            { "hud.stage", 2 },
            { "hud.progress", 2 },
            { "hud.run", 2 },
            { "result.score", 3 },
            { "result.rank", 1 },
            { "result.run", 3 },
            { "stage.number", 1 },
            { "ranking.number", 1 },
            { "combo.count", 1 }, { "combo.ready", 0 }, { "combo.progress", 2 },
            { "combo.use_hint", 0 }, { "combo.landing_hint", 0 }, { "combo.perfect", 1 },
            { "combo.broken", 0 }, { "combo.used", 0 }, { "combo.shortcut", 0 },
            { "combo.safe_route", 0 }, { "combo.rejoin", 0 },
        };
    }
}
